<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Resource</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="SharedResources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>SharedResources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="SharedResources.kk.resx">
        <DependentUpon>SharedResources.resx</DependentUpon>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="SharedResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>SharedResources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
